name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.jsx'

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ✅ Required to access full history (e.g., main branch)

      - name: Fetch main branch explicitly
        run: git fetch origin main # ✅ Ensures origin/main exists for git diff

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install openai @octokit/rest

      - name: Run OpenAI PR Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_CODEX_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node analyze.mjs
